package maximumSubarray;

import java.util.Arrays;

/*****************************************************************************************************************************************
 * The first thing that we can do is find out all the sub-arrays and then find their sum and compare it with the sum of other sub-arrays
 *****************************************************************************************************************************************/
public class Solution1 {

    public static void main(String args[])
    {
        //The first step is to get the input array.
        int[] arr = {-1,2,-5,7};

        //Find the minimum of the array
        int[] arr1 = arr;
        Arrays.sort(arr1);
        int maxSum = arr1[0];

        //The sequences can be generated by taking one element and then moving j (loop-2) over the array
        for(int i=0; i<arr.length;i++)
        {
            for(int j=0; j<arr.length;j++)
            {
                int sum =0;
                for(int k=i; k<j+1;k++)
                {
                    sum=sum+arr[k];
                }
                maxSum = Math.max(maxSum,sum);
            }
        }
    }
}
